name: import_lint
description: The Import Lint package defines import lint rules and report on
  lints found in Dart code.
version: 0.9.0
homepage: https://kawa.dev
repository: https://github.com/kawa1214/import-lint

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=3.4.0 <4.1.0"
  analyzer_plugin: ">=0.8.0 <0.10.0"
  args: ^2.3.0
  cli_util: ^0.3.5
  glob: ^2.0.2
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  coverage: 1.3.2
  linter: 1.22.0
  lints: 2.0.0
  test: 1.21.1
